In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_excel("../DataSet/Superstore.xls")

In [5]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.info()

Rows: 10194
Columns: 21
<class 'pandas.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  str
 2   Order Date      10194 non-null  datetime64[us]
 3   Ship Date       10194 non-null  datetime64[us]
 4   Ship Mode       10194 non-null  str
 5   Customer ID     10194 non-null  str
 6   Customer Name   10194 non-null  str
 7   Segment         10194 non-null  str
 8   Country/Region  10194 non-null  str
 9   City            10194 non-null  str
 10  State/Province  10194 non-null  str
 11  Postal Code     10194 non-null  object
 12  Region          10194 non-null  str
 13  Product ID      10194 non-null  str
 14  Category        10194 non-null  str
 15  Sub-Category    10194 non-null  str
 16  Product Name    10194 non-null  str
 17  Sales           10194 non-null  float64
 18  Quantity        10194 non-null  int64
 19  Discount        10194 non-null  float64
 20  Profit          10194 non-null  float64
dtypes: datetime64[us](2), float64(3), int64(2), object(1), str(13)
memory usage: 1.6+ MB

In [7]:
missing_values = df.isnull().sum()

missing_values.to_frame(name="Missing Values")

                Missing Values
Row ID                       0
Order ID                     0
Order Date                   0
Ship Date                    0
Ship Mode                    0
Customer ID                  0
Customer Name                0
Segment                      0
Country/Region               0
City                         0
State/Province               0
Postal Code                  0
Region                       0
Product ID                   0
Category                     0
Sub-Category                 0
Product Name                 0
Sales                        0
Quantity                     0
Discount                     0
Profit                       0

In [11]:
duplicate_count = df.duplicated().sum()

print("Duplicate Rows:",duplicate_count)

Duplicate Rows: 0

In [12]:
print("Total Rows:", len(df))
print("Rows after removing duplicates:", len(df.drop_duplicates()))

Total Rows: 10194
Rows after removing duplicates: 10194

In [15]:
print("Total rows:", len(df))
print("Unique Order IDs:", df["Order ID"].nunique())
print("Duplicate Order ID rows:", df["Order ID"].duplicated().sum())

Total rows: 10194
Unique Order IDs: 5111
Duplicate Order ID rows: 5083

In [16]:
print("Order Date dtype:", df["Order Date"].dtype)
print("Minimum Order Date:", df["Order Date"].min())
print("Maximum Order Date:", df["Order Date"].max())

Order Date dtype: datetime64[us]
Minimum Order Date: 2023-01-03 00:00:00
Maximum Order Date: 2026-12-30 00:00:00

In [17]:
print("Missing Dates:", df["Order Date"].isnull().sum())

Missing Dates: 0

In [18]:
df[["Sales", "Profit", "Quantity", "Discount"]].describe()

              Sales        Profit      Quantity      Discount
count  10194.000000  10194.000000  10194.000000  10194.000000
mean     228.225854     28.673417      3.791838      0.155385
std      619.906839    232.465115      2.228317      0.206249
min        0.444000  -6599.978000      1.000000      0.000000
25%       17.220000      1.760800      2.000000      0.000000
50%       53.910000      8.690000      3.000000      0.200000
75%      209.500000     29.297925      5.000000      0.200000
max    22638.480000   8399.976000     14.000000      0.800000

In [19]:
print("Sales <= 0 :", (df["Sales"] <= 0).sum())
print("Quantity <= 0 :", (df["Quantity"] <= 0).sum())
print("Discount < 0 :", (df["Discount"] < 0).sum())
print("Discount > 1 :", (df["Discount"] > 1).sum())

Sales <= 0 : 0
Quantity <= 0 : 0
Discount < 0 : 0
Discount > 1 : 0

In [20]:
print("Negative Profit Rows:", (df["Profit"] < 0).sum())

Negative Profit Rows: 1901

In [21]:
print("Categories:")
print(df["Category"].unique())

print("\nSub-Categories:")
print(df["Sub-Category"].unique())

print("\nRegions:")
print(df["Region"].unique())

print("\nSegments:")
print(df["Segment"].unique())

print("\nShip Modes:")
print(df["Ship Mode"].unique())

Categories:
<StringArray>
['Office Supplies', 'Furniture', 'Technology']
Length: 3, dtype: str

Sub-Categories:
<StringArray>
[      'Paper',     'Binders',      'Labels',     'Storage',         'Art',
      'Chairs',   'Fasteners',      'Phones', 'Furnishings', 'Accessories',
   'Bookcases',   'Envelopes',  'Appliances',      'Tables',    'Supplies',
    'Machines',     'Copiers']
Length: 17, dtype: str

Regions:
<StringArray>
['Central', 'East', 'South', 'West']
Length: 4, dtype: str

Segments:
<StringArray>
['Consumer', 'Home Office', 'Corporate']
Length: 3, dtype: str

Ship Modes:
<StringArray>
['Standard Class', 'First Class', 'Second Class', 'Same Day']
Length: 4, dtype: str

In [24]:
df.dtypes

Row ID                     int64
Order ID                     str
Order Date        datetime64[us]
Ship Date         datetime64[us]
Ship Mode                    str
Customer ID                  str
Customer Name                str
Segment                      str
Country/Region               str
City                         str
State/Province               str
Postal Code               object
Region                       str
Product ID                   str
Category                     str
Sub-Category                 str
Product Name                 str
Sales                    float64
Quantity                   int64
Discount                 float64
Profit                   float64
dtype: object

In [25]:
validation_report = {
    "Total Rows": len(df),
    "Total Columns": len(df.columns),
    "Missing Values": df.isnull().sum().sum(),
    "Duplicate Rows": df.duplicated().sum(),
    "Unique Orders": df["Order ID"].nunique(),
    "Unique Customers": df["Customer Name"].nunique(),
    "Unique Products": df["Product Name"].nunique(),
    "Negative Profit Rows": (df["Profit"] < 0).sum(),
    "Non-positive Sales": (df["Sales"] <= 0).sum(),
    "Non-positive Quantity": (df["Quantity"] <= 0).sum(),
    "Invalid Discounts": ((df["Discount"] < 0) | (df["Discount"] > 1)).sum(),
    "Missing Dates": df["Order Date"].isnull().sum()
}

validation_report

{'Total Rows': 10194,
 'Total Columns': 21,
 'Missing Values': np.int64(0),
 'Duplicate Rows': np.int64(0),
 'Unique Orders': 5111,
 'Unique Customers': 800,
 'Unique Products': 1849,
 'Negative Profit Rows': np.int64(1901),
 'Non-positive Sales': np.int64(0),
 'Non-positive Quantity': np.int64(0),
 'Invalid Discounts': np.int64(0),
 'Missing Dates': np.int64(0)}

In [ ]:
# Data Validation Conclusion

The dataset successfully passed the final data validation checks.

- The dataset contains **10,194 rows and 21 columns**.
- There are **no missing values**.
- There are **no completely duplicated rows**.
- There are **5,111 unique orders**, **800 unique customers**, and **1,849 unique products**.
- Order Date and Ship Date are correctly stored as datetime values.
- Sales and Quantity contain no zero or negative values.
- Discount values are within the valid range of 0 to 0.8.
- There are **1,901 negative-profit transactions**, which represent legitimate loss-making business transactions and should not be removed.
- The categorical columns contain consistent and expected values.
- Postal Code is stored as an object/string type, which is appropriate because postal codes are identifiers rather than numerical measures.

### Final Conclusion

The dataset is considered **clean, consistent, and ready for dashboard development and further analysis**.

No additional data-cleaning operations are required at this stage.

In [ ]:
# Dashboard Data Preparation

In [27]:
dashboard_df = df.copy()

print("Dashboard Dataset Shape:", dashboard_df.shape)

Dashboard Dataset Shape: (10194, 21)

In [28]:
dashboard_df["Year"] = dashboard_df["Order Date"].dt.year
dashboard_df["Month"] = dashboard_df["Order Date"].dt.month
dashboard_df["Month Name"] = dashboard_df["Order Date"].dt.month_name()
dashboard_df["Quarter"] = dashboard_df["Order Date"].dt.quarter

In [29]:
dashboard_df["Month Start"] = dashboard_df["Order Date"].dt.to_period("M").dt.to_timestamp()

In [30]:
dashboard_df[["Order Date", "Year", "Month", "Month Name", "Quarter", "Month Start"]].head()

  Order Date  Year  Month Month Name  Quarter Month Start
0 2023-01-03  2023      1    January        1  2023-01-01
1 2023-01-04  2023      1    January        1  2023-01-01
2 2023-01-04  2023      1    January        1  2023-01-01
3 2023-01-04  2023      1    January        1  2023-01-01
4 2023-01-05  2023      1    January        1  2023-01-01

In [31]:
dashboard_df["Profit Margin (%)"] = (
    dashboard_df["Profit"] / dashboard_df["Sales"]
) * 100

In [32]:
dashboard_df[["Sales", "Profit", "Profit Margin (%)"]].head()

     Sales   Profit  Profit Margin (%)
0   16.448   5.5512              33.75
1    3.540  -5.4870            -155.00
2   11.784   4.2717              36.25
3  272.736 -64.7748             -23.75
4   19.536   4.8840              25.00

In [33]:
dashboard_df["Shipping Days"] = (
    dashboard_df["Ship Date"] - dashboard_df["Order Date"]
).dt.days

In [34]:
dashboard_df[["Order Date", "Ship Date", "Shipping Days"]].head()

  Order Date  Ship Date  Shipping Days
0 2023-01-03 2023-01-07              4
1 2023-01-04 2023-01-08              4
2 2023-01-04 2023-01-08              4
3 2023-01-04 2023-01-08              4
4 2023-01-05 2023-01-12              7

In [35]:
dashboard_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 28 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Row ID             10194 non-null  int64
 1   Order ID           10194 non-null  str
 2   Order Date         10194 non-null  datetime64[us]
 3   Ship Date          10194 non-null  datetime64[us]
 4   Ship Mode          10194 non-null  str
 5   Customer ID        10194 non-null  str
 6   Customer Name      10194 non-null  str
 7   Segment            10194 non-null  str
 8   Country/Region     10194 non-null  str
 9   City               10194 non-null  str
 10  State/Province     10194 non-null  str
 11  Postal Code        10194 non-null  object
 12  Region             10194 non-null  str
 13  Product ID         10194 non-null  str
 14  Category           10194 non-null  str
 15  Sub-Category       10194 non-null  str
 16  Product Name       10194 non-null  str
 17  Sales              10194 non-null  float64
 18  Quantity           10194 non-null  int64
 19  Discount           10194 non-null  float64
 20  Profit             10194 non-null  float64
 21  Year               10194 non-null  int32
 22  Month              10194 non-null  int32
 23  Month Name         10194 non-null  str
 24  Quarter            10194 non-null  int32
 25  Month Start        10194 non-null  datetime64[us]
 26  Profit Margin (%)  10194 non-null  float64
 27  Shipping Days      10194 non-null  int64
dtypes: datetime64[us](3), float64(4), int32(3), int64(3), object(1), str(14)
memory usage: 2.1+ MB

In [36]:
dashboard_df[
    [
        "Order Date",
        "Ship Date",
        "Year",
        "Month",
        "Month Name",
        "Quarter",
        "Month Start",
        "Sales",
        "Profit",
        "Profit Margin (%)",
        "Quantity",
        "Discount",
        "Shipping Days"
    ] 
].head()

,Order Date,Ship Date,Year,Month,Month Name,Quarter,Month Start,Sales,Profit,Profit Margin (%),Quantity,Discount,Shipping Days
0,2023-01-03,2023-01-07,2023,1,January,1,2023-01-01,16.448,5.5512,33.75,2,0.2,4
1,2023-01-04,2023-01-08,2023,1,January,1,2023-01-01,3.540,-5.4870,-155.00,2,0.8,4
2,2023-01-04,2023-01-08,2023,1,January,1,2023-01-01,11.784,4.2717,36.25,3,0.2,4
3,2023-01-04,2023-01-08,2023,1,January,1,2023-01-01,272.736,-64.7748,-23.75,3,0.2,4
4,2023-01-05,2023-01-12,2023,1,January,1,2023-01-01,19.536,4.8840,25.00,3,0.2,7

In [37]:
print("Minimum Shipping Days:", dashboard_df["Shipping Days"].min())
print("Maximum Shipping Days:", dashboard_df["Shipping Days"].max())
print("Average Shipping Days:", dashboard_df["Shipping Days"].mean())

Minimum Shipping Days: 0
Maximum Shipping Days: 11
Average Shipping Days: 3.9613498136158523

In [38]:
print(
    "Invalid Shipping Days:",
    (dashboard_df["Shipping Days"] < 0).sum()
)

Invalid Shipping Days: 0

In [39]:
dashboard_df.isnull().sum().sum()

np.int64(0)

In [40]:
dashboard_df.duplicated().sum()

np.int64(0)

In [41]:
print("Rows:", len(dashboard_df))
print("Columns:", len(dashboard_df.columns))

Rows: 10194
Columns: 28

In [ ]:
# Final Dashboard Dataset

In [42]:
print("Missing values:", dashboard_df.isnull().sum().sum())
print("Duplicate rows:", dashboard_df.duplicated().sum())
print("Rows:", len(dashboard_df))
print("Columns:", len(dashboard_df.columns))

Missing values: 0
Duplicate rows: 0
Rows: 10194
Columns: 28

In [43]:
file_path = "../DataSet/Sales_Performance_Dashboard_Final.csv"

dashboard_df.to_csv(file_path, index=False)

print("Final dashboard dataset saved successfully!")
print("Location:", file_path)

Final dashboard dataset saved successfully!
Location: ../DataSet/Sales_Performance_Dashboard_Final.csv

In [44]:
import os

file_path = "../DataSet/Sales_Performance_Dashboard_Final.csv"

print("File exists:", os.path.exists(file_path))

if os.path.exists(file_path):
    print("File size:", round(os.path.getsize(file_path) / 1024, 2), "KB")

File exists: True
File size: 2870.12 KB

In [45]:
final_df = pd.read_csv(file_path)

print("Loaded successfully!")
print("Shape:", final_df.shape)
print("\nColumns:")
print(final_df.columns.tolist())

Loaded successfully!
Shape: (10194, 28)

Columns:
['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country/Region', 'City', 'State/Province', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit', 'Year', 'Month', 'Month Name', 'Quarter', 'Month Start', 'Profit Margin (%)', 'Shipping Days']